Add option for tabindex attribute
arve0/markdown-it-implicit-figures pull request #15
Opened 2016-12-03 04:53 UTC by huw

This was useful for a personal project, inspired by [this css-trick](https://css-tricks.com/expanding-images-html5/). If you don't think it's appropriate for the master branch here, I'm happy to close this request 🙂.

2016-12-03 09:31 UTC, arve0 commented
I like it. :+1: Gives something extra that are less elegant with [attrs](https://www.npmjs.com/package/markdown-it-attrs).

2016-12-04 12:05 UTC, arve0 requested changes
Please take a look at the comments.

2016-12-04 12:05 UTC, arve0 commented on index.js
> +  var tabIndex = 1;
This should be inside `function implicitFigures`, to have it reset upon each `md.render()`.

2016-12-04 12:05 UTC, arve0 commented on package.json
> +  "version": "0.4.0",
I'll bump version on publishing, please remove this.

2016-12-04 12:05 UTC, arve0 commented on test.js
> +  it('should add incremental tabindex to figures when opts.tabindex is set', function () {
Add a test to check that `tabIndex` is reset between each `md.render()`.

2016-12-05 02:13 UTC, huw commented on test.js
> +  it('should add incremental tabindex to figures when opts.tabindex is set', function () {
Let me know if you think the proposed test is sensible—I don't change the source or expected output, just render and compare twice.

2016-12-05 05:02 UTC, arve0 commented on test.js
> +  it('should add incremental tabindex to figures when opts.tabindex is set', function () {
:+1:

2016-12-05 05:46 UTC, arve0 commented
Thanks for this. I've merged locally. Released in `v0.5.0`.

2016-12-05 05:46 UTC, closed without merging